name: Breaking The Get Fit Myth
favicon: null
layout_spectrum: 0.4179659604560584
typography_spectrum: 0.9387920475564897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.34972804225981236
  lightness: 0.6411203576717526
  saturation: 0.3686705876607448
  rhythmicContrast: 0.2532595149241388
purpose: []
